INSERT INTO invoice (customer_name, amount, description) VALUES
('John Doe', 150.00, 'Invoice for July services'),
('Jane Smith', 200.00, 'Invoice for August services'),
('Alice Johnson', 250.00, 'Invoice for September services'),
('Bob Brown', 300.00, 'Invoice for October services'),
('Carol White', 350.00, 'Invoice for November services'),
('Dave Black', 400.00, 'Invoice for December services'),
('Eve Green', 450.00, 'Invoice for January services'),
('Frank Blue', 500.00, 'Invoice for February services'),
('Grace Purple', 550.00, 'Invoice for March services'),
('Hank Yellow', 600.00, 'Invoice for April services');
